# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: pip Install Test (nightly)

on:
  schedule:
    # 10 am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  workflow_dispatch: {}

jobs:
  run-pip-install:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r https://raw.githubusercontent.com/google-ai-edge/ai-edge-torch/main/requirements.txt
      - name: Install ai-edge-torch
        run: |
          pip install ai-edge-torch
      - name: Import ai-edge-torch
        run: |
          python -c "import ai_edge_torch"
